### ISSUE TITLE
JS script issue

### ISSUE THREAD

**Issue by oisis** [pavel-kazhavets/AlertmanagerRocketChat#3]
Hi,
 I am trying to integrate AlertManager with Rocket.Chat and i got this error:
```bash
[34mI20180302-09:58:43.186(0) rocketchat_logger rocketchat_logger.js:278 [31mIntegrations ➔ Incoming WebHook.error [Stack:] 
[34mI20180302-09:58:43.186(0) rocketchat_logger rocketchat_logger.js:278 [31mIntegrations ➔ Incoming WebHook.error   script.js:1   function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function")}}var Script=function(){function Script(){_classCallCheck(this,Script)}Script.prototype.process_incoming_request=function process_incoming_request(_ref){var request=_ref.request;var alertColor="warning";if(request.content.status=="resolved"){alertColor="good"}else if(request.content.status=="firing"){alertColor="danger"}console.log(request.content);var finFields=[];for(i=0;i<request.content.alerts.length;i++){var endVal=request.content.alerts[i];var elem={title:"alertname: "+endVal.labels.alertname,value:"*instance:* "+endVal.labels.instance,short:false};finFields.push(elem);finFields.push({title:"description",value:endVal.annotations.description});finFields.push({title:"summary",value:endVal.annotations.summary})}return{content:{username:"Prometheus Alert",attachments:[{color:alertColor,title_link:request.content.externalURL,title:"Prometheus notification      TypeError: Cannot read property 'length' of undefined       at Script.process_incoming_request (script.js:1:544)       at evalmachine.<anonymous>:1:8       at ContextifyScript.Script.runInContext (vm.js:59:29)       at ContextifyScript.Script.runInNewContext (vm.js:65:15)       at Object.runInNewContext (vm.js:135:38)       at Object.executeIntegrationRest [as action] (meteor://app/packages/rocketchat_integrations.js:2384:22)       at Route.share.Route.Route._callEndpoint (meteor://app/packages/nimble_restivus.js:358:32)       at meteor://app/packages/nimble_restivus.js:247:33       at packages/simple_json-routes.js:98:9
```

AlertManager version: v0.14.0
Rocket.Chat version: 0.61.2

**Comment by oisis** [comment]
Sorry my bad. All is ok.
